inputs = ["movies/Mario is Missing! (U)-0.fm2",
"movies/Mario's Time Machine! (U)-0.fm2",
"movies/Mega Man 2 (U)-0.fm2",
"movies/Mega Man 3 (U) [!]-0.fm2",
"movies/Mega Man 4 (U)-0.fm2",
"movies/Mega Man 5 (U)-0.fm2",
"movies/Mega Man 6 (U)-0.fm2",
"movies/Metroid (U)-0.fm2",
"movies/Mighty Bomb Jack (U)-0.fm2",
"movies/Ninja Gaiden (USA)-0.fm2",
"movies/Ninja Gaiden Episode II - The Dark Sword of Chaos (USA)-0.fm2",
"movies/Ninja Gaiden Episode III - The Ancient Ship of Doom (USA)-0.fm2",
"movies/Super C (USA)-0.fm2",
"movies/Super Mario Bros - Duck Hunt (U)-0.fm2",
"movies/Super Mario Bros (JU) (PRG 0)-0.fm2",
"movies/Super Mario Bros 2 (different levels) [p2][!]-luigi-0.fm2",
"movies/Super Mario Bros 2 (different levels) [p2][!]-mario-0.fm2",
"movies/Super Mario Bros 2 (U) (PRG 0)-Luigi-0.fm2",
"movies/Super Mario Bros 2 (U) (PRG 0)-mario-0.fm2",
"movies/Super Mario Bros 2 (U) (PRG 0)-Peach-0.fm2",
"movies/Super Mario Bros 2 (U) (PRG 0)-Toad-0.fm2",
"movies/Super Mario Bros 3 (U) (PRG 0)-mario-0.fm2",
"movies/Takahashi Meijin no Bouken Jima IV (Japan) [En by Demiforce v1.0] (~Adventure Island IV)-0.fm2",
"movies/Teenage Mutant Ninja Turtles (USA)-0.fm2",
"movies/Teenage Mutant Ninja Turtles II - The Arcade Game (USA)-0.fm2",
"movies/Zelda 2 - The Adventure of Link (U)-0.fm2",]

roms = [
"movies/Mega Man (USA).nes",
"movies/Addams Family - Pugsley's Scavenger Hunt, The (U).nes",
"movies/Addams Family, The (U).nes",
"movies/Amagon (U) [a1].nes",
"movies/Balloon Fight (JU).nes",
"movies/Batman - Return of the Joker (U).nes",
"movies/Batman (U).nes",
"movies/Batman Returns (U).nes",
"movies/Battletoads (U).nes",
"movies/Bubble Bobble (U).nes",
"movies/Clash At Demonhead (U) [a1].nes",
"movies/Donkey Kong (JU).nes",
"movies/Donkey Kong Jr. (JU).nes",
"movies/Donkey Kong Jr. Math (U).nes",
"movies/Double Dragon (U).nes",
"movies/Double Dragon 2 - The Revenge (U).nes",
"movies/Double Dragon 3 - The Sacred Stones (U).nes",
"movies/Ghosts'n Goblins (USA).nes",
"movies/Hudson's Adventure Island (USA).nes",
"movies/Hudson's Adventure Island II (USA).nes",
"movies/Hudson's Adventure Island III (USA).nes",
"movies/Ice Climber (JE).nes",
"movies/Kid Icarus (UE).nes",
"movies/Kirby's Adventure (U) (PRG 0).nes",
"movies/Mario Bros (JU).nes",
"movies/Mario is Missing! (U).nes",
"movies/Mario's Time Machine! (U).nes",
"movies/Mega Man 2 (U).nes",
"movies/Mega Man 3 (U) [!].nes",
"movies/Mega Man 4 (U).nes",
"movies/Mega Man 5 (U).nes",
"movies/Mega Man 6 (U).nes",
"movies/Metroid (U).nes",
"movies/Mighty Bomb Jack (U).nes",
"movies/Ninja Gaiden (USA).nes",
"movies/Ninja Gaiden Episode II - The Dark Sword of Chaos (USA).nes",
"movies/Ninja Gaiden Episode III - The Ancient Ship of Doom (USA).nes",
"movies/Super C (USA).nes",
"movies/Super Mario Bros - Duck Hunt (U).nes",
"movies/Super Mario Bros (JU) (PRG 0).nes",
"movies/Super Mario Bros 2 (different levels) [p2][!].nes",
"movies/Super Mario Bros 2 (different levels) [p2][!].nes",
"movies/Super Mario Bros 2 (U) (PRG 0).nes",
"movies/Super Mario Bros 2 (U) (PRG 0).nes",
"movies/Super Mario Bros 2 (U) (PRG 0).nes",
"movies/Super Mario Bros 2 (U) (PRG 0).nes",
"movies/Super Mario Bros 3 (U) (PRG 0).nes",
"movies/Takahashi Meijin no Bouken Jima IV (Japan) [En by Demiforce v1.0] (~Adventure Island IV).nes",
"movies/Teenage Mutant Ninja Turtles (USA).nes",
"movies/Teenage Mutant Ninja Turtles II - The Arcade Game (USA).nes",
"movies/Zelda 2 - The Adventure of Link (U).nes",]


outputs = ["MegaManU-0.HA",
"AddamsFamily-PugsleysScavengerHunt,TheU-0.HA",
"AddamsFamily,TheU-0.HA",
"AmagonU[a1]-0.HA",
"BalloonFightJU-0.HA",
"Batman-ReturnoftheJokerU-0.HA",
"BatmanU-0.HA",
"BatmanReturnsU-0.HA",
"BattletoadsU-0.HA",
"BubbleBobbleU-0.HA",
"ClashAtDemonheadU[a1]-0.HA",
"DonkeyKongJU-0.HA",
"DonkeyKongJr.JU-0.HA",
"DonkeyKongJr.MathU-0.HA",
"DoubleDragonU-0.HA",
"DoubleDragon2-TheRevengeU-0.HA",
"DoubleDragon3-TheSacredStonesU-0.HA",
"GhostsnGoblinsUSA-2.HA",
"HudsonsAdventureIslandUSA-0.HA",
"HudsonsAdventureIslandIIUSA-0.HA",
"HudsonsAdventureIslandIIIUSA-0.HA",
"IceClimberJE-0.HA",
"KidIcarusUE-0.HA",
"KirbysAdventureUPRG0-0.HA",
"MarioBrosJU-0.HA",
"MarioisMissing!U-0.HA",
"MariosTimeMachine!U-0.HA",
"MegaMan2U-0.HA",
"MegaMan3U[!]-0.HA",
"MegaMan4U-0.HA",
"MegaMan5U-0.HA",
"MegaMan6U-0.HA",
"MetroidU-0.HA",
"MightyBombJackU-0.HA",
"NinjaGaidenUSA-0.HA",
"NinjaGaidenEpisodeII-TheDarkSwordofChaosUSA-0.HA",
"NinjaGaidenEpisodeIII-TheAncientShipofDoomUSA-0.HA",
"SuperCUSA-0.HA",
"SuperMarioBros-DuckHuntU-0.HA",
"SuperMarioBrosJUPRG0-0.HA",
"SuperMarioBros2differentlevels[p2][!]-luigi-0.HA",
"SuperMarioBros2differentlevels[p2][!]-mario-0.HA",
"SuperMarioBros2UPRG0-Luigi-0.HA",
"SuperMarioBros2UPRG0-mario-0.HA",
"SuperMarioBros2UPRG0-Peach-0.HA",
"SuperMarioBros2UPRG0-Toad-0.HA",
"SuperMarioBros3UPRG0-mario-0.HA",
"TakahashiMeijinnoBoukenJimaIVJapan[EnbyDemiforcev1.0]AdventureIslandIV-0.HA",
"TeenageMutantNinjaTurtlesUSA-0.HA",
"TeenageMutantNinjaTurtlesII-TheArcadeGameUSA-0.HA",
"Zelda2-TheAdventureofLinkU-0.HA",]

import os

for movie,rom, output in zip(inputs,roms,outputs):
    command='time python jump_from_tracks.py "{}" "{}" 1 2 120 2 {} > "{}"'.format(rom,movie,output,output)
    print'RUNNING',command
    os.system(command)
